// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdE7C66gEhV8yYMr_cJmS2Os3drXJ8oY0',
    appId: '1:22224951379:web:dc4c6a26aeac0fe6434ea6',
    messagingSenderId: '22224951379',
    projectId: 'expense-tracker-24587',
    authDomain: 'expense-tracker-24587.firebaseapp.com',
    storageBucket: 'expense-tracker-24587.firebasestorage.app',
    measurementId: 'G-HWWCVD3LZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdM-kFlZdDdkEAVqibtO-0zxGAQqMyP5M',
    appId: '1:22224951379:android:ba3611f79f647072434ea6',
    messagingSenderId: '22224951379',
    projectId: 'expense-tracker-24587',
    storageBucket: 'expense-tracker-24587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANZdGYbYjiTvzKW-_xF86I2nk8Gx0HYJs',
    appId: '1:22224951379:ios:3220c098f08aae3a434ea6',
    messagingSenderId: '22224951379',
    projectId: 'expense-tracker-24587',
    storageBucket: 'expense-tracker-24587.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANZdGYbYjiTvzKW-_xF86I2nk8Gx0HYJs',
    appId: '1:22224951379:ios:3220c098f08aae3a434ea6',
    messagingSenderId: '22224951379',
    projectId: 'expense-tracker-24587',
    storageBucket: 'expense-tracker-24587.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdE7C66gEhV8yYMr_cJmS2Os3drXJ8oY0',
    appId: '1:22224951379:web:61f431f6dfa587c0434ea6',
    messagingSenderId: '22224951379',
    projectId: 'expense-tracker-24587',
    authDomain: 'expense-tracker-24587.firebaseapp.com',
    storageBucket: 'expense-tracker-24587.firebasestorage.app',
    measurementId: 'G-Q9QVMD6G49',
  );
}
